version: '3'

services:

  testing-system-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - testing-system-php-fpm
    ports:
      - "8080:80"
  testing-system-php-fpm:
      build:
        context: ./docker
        dockerfile: php-fpm.docker
      volumes:
        - ./:/app
      depends_on:
        - testing-system-postgres
  testing-system-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - testing-system-postgres
  testing-system-postgres:
      image: postgres:11.2-alpine
      volumes:
        - testing-system-postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: app
      ports:
        - "54321:5432"
volumes:
  testing-system-postgres:
  composer: